// Generated by CoffeeScript 2.7.0
  // cssUtils.coffee
import {
  undef
} from '@jdeighan/base-utils';

// ---------------------------------------------------------------------------
export var getCSSVar = (name, elem = undef) => {
  if (elem === undef) {
    elem = document;
  }
  return getComputedStyle(elem).getPropertyValue(name);
};

// ---------------------------------------------------------------------------
export var setCSSVar = (name, value, elem = undef) => {
  if (elem === undef) {
    elem = document;
  }
  elem.style.setProperty(name, value);
};

//# sourceMappingURL=cssUtils.js.map
