// Generated by CoffeeScript 2.7.0
  // prefs.coffee
import {
  getLocalStore
} from '@jdeighan/coffee-utils/browser';

export var hPrefs = getLocalStore('hPrefs', {});

// ---------------------------------------------------------------------------
export var setPref = (key, value) => {
  hPrefs[key] = value;
  return setLocalStore('hPrefs', hPrefs);
};
