// Generated by CoffeeScript 2.7.0
(function() {
  var i, j;

  for (i = j = 1; j <= 10; i = ++j) {
    if (i % 2 === 0) {
      console.log(`${i} is even!`);
    } else {
      console.log(`${i} is odd!`);
    }
  }

}).call(this);
