// Generated by CoffeeScript 2.5.1
// 03heredoc.test.coffee
var tester;

import {
  numHereDocs,
  patch,
  build
} from '../src/heredoc_utils.js';

import {
  AvaTester
} from '@jdeighan/ava-tester';

tester = new AvaTester();

// ---------------------------------------------------------------------------
tester.equal(11, numHereDocs("where <<"), 0);

tester.equal(12, numHereDocs("where <<<"), 1);

tester.equal(13, numHereDocs("where <<< is <<<"), 2);

tester.equal(14, numHereDocs("where <<< is <<< or <<<"), 3);

// ---------------------------------------------------------------------------
tester.equal(18, build(['a multi', 'line string']), "a multi\nline string\n");

// ---------------------------------------------------------------------------
tester.equal(26, patch("let x = <<<;", [['a multi', 'line string']]), "let x = \"a multi\\nline string\\n\";");

// ---------------------------------------------------------------------------
tester.equal(35, build(['\t\ta multi', '\t\tline string']), "a multi\nline string\n");

// ---------------------------------------------------------------------------
tester.equal(43, patch("let x = <<<; let y = <<<;", [['\t\ta multi', '\t\tline string'], ['\ta new', '\tstring']]), "let x = \"a multi\\nline string\\n\"; let y = \"a new\\nstring\\n\";");

// ---------------------------------------------------------------------------
tester.equal(54, build(void 0), '');

tester.equal(55, build(null), '');

tester.equal(56, build([]), '');

// --- build standard HEREDOC
tester.equal(60, build(['first line', 'second line']), "first line\nsecond line\n");

// --- TAML
tester.equal(68, build(['---', '- first', '- second']), ['first', 'second']);

tester.equal(72, build(['---', 'key: first', 'value: second']), {
  key: "first",
  value: "second"
});

// ---------------------------------------------------------------------------
tester.equal(79, patch("let lItems = <<<;", [['---', '- one', '- two']]), 'let lItems = ["one","two"];');

// ---------------------------------------------------------------------------
tester.equal(89, patch("let lItems = <<<;", [['---', 'key: one', 'value: two']]), 'let lItems = {"key":"one","value":"two"};');
