// Generated by CoffeeScript 2.5.1
// temp.coffee
var n;

import {
  say
} from '@jdeighan/coffee-utils';

// ---------------------------------------------------------------------------
n = new Number(42);

if (Number.isInteger(n)) {
  say("yes");
} else {
  say("no");
}
