// Generated by CoffeeScript 2.5.1
// temp.coffee
var main, testDir;

import {
  log
} from '@jdeighan/coffee-utils/log';

import {
  mydir,
  forEachFile
} from '@jdeighan/coffee-utils/fs';

import {
  debug,
  setDebugging
} from '@jdeighan/coffee-utils/debug';

testDir = mydir(import.meta.url);

// ---------------------------------------------------------------------------
main = function() {
  var callback;
  callback = function(fname, dir, level) {
    return log(`${'   '.repeat(level)}  ${fname} in ${dir}`);
  };
  return forEachFile(testDir, callback, /\.txt$/);
};

// ---------------------------------------------------------------------------
main();
