// Generated by CoffeeScript 2.6.1
// temp.coffee
var str;

import {
  hashToStr
} from '@jdeighan/coffee-utils';

// ---------------------------------------------------------------------------
str = hashToStr({
  c: 3,
  b: 2,
  a: 1
});

console.log(str);
