// Generated by CoffeeScript 2.6.1
// temp.coffee
var dir;

import {
  say
} from '@jdeighan/coffee-utils';

import {
  log
} from '@jdeighan/coffee-utils/log';

import {
  setDebugging
} from '@jdeighan/coffee-utils/debug';

import {
  mydir,
  mkpath
} from '@jdeighan/coffee-utils/fs';

setDebugging(true);

dir = mydir(import.meta.url);

say(`dir = ${dir}`);
