// Generated by CoffeeScript 2.6.1
// arrow.coffee
var arrowhead, corner, hbar, oneIndent, vbar;

vbar = '│'; // unicode 2502

hbar = '─'; // unicode 2500

corner = '└'; // unicode 2514

arrowhead = '>';

oneIndent = vbar + '   ';

export var arrow = corner + hbar + arrowhead + ' ';

// ---------------------------------------------------------------------------
export var getPrefix = function(level, withArrow) {
  if (withArrow) {
    return oneIndent.repeat(level - 1) + arrow;
  } else {
    return oneIndent.repeat(level);
  }
};

// ---------------------------------------------------------------------------
export var hasArrow = function(str) {
  return str.indexOf(arrow) > -1;
};

// ---------------------------------------------------------------------------
export var removeArrow = function(str, useVbar) {
  if (hasArrow(str)) {
    if (useVbar) {
      return str.replace(arrow, oneIndent);
    } else {
      return str.replace(arrow, '    ');
    }
  } else {
    return str;
  }
};

// ---------------------------------------------------------------------------
