// Generated by CoffeeScript 2.7.0
  // arrow.coffee
import {
  assert
} from '@jdeighan/exceptions';

import {
  undef,
  OL,
  setCharsAt
} from '@jdeighan/coffee-utils';

// --- We use spaces here because Windows Terminal handles TAB chars badly
export var vbar = '│'; // unicode 2502

export var hbar = '─'; // unicode 2500

export var corner = '└'; // unicode 2514

export var arrowhead = '>';

export var space = ' ';

export var dot = '.';

export var oneIndent = vbar + space + space + space;

export var arrow = corner + hbar + arrowhead + space;

export var clearIndent = space + space + space + space;

export var dotIndent = dot + space + space + space;

// ---------------------------------------------------------------------------
export var prefix = function(level, option = 'none') {
  switch (option) {
    case 'withArrow':
      if (level === 0) {
        return arrow;
      } else {
        return oneIndent.repeat(level - 1) + arrow;
      }
      break;
    case 'noLastVbar':
      assert(level >= 1, `prefix(), noLastVbar but level=${OL(level)}`);
      return oneIndent.repeat(level - 1) + clearIndent;
    case 'noLast2Vbars':
      assert(level >= 2, `prefix(), noLast2Vbars but level=${OL(level)}`);
      return oneIndent.repeat(level - 2) + clearIndent + clearIndent;
    case 'dotLastVbar':
      assert(level >= 1, `prefix(), dotLastVbar but level=${OL(level)}`);
      return oneIndent.repeat(level - 1) + dotIndent;
    case 'dotLast2Vbars':
      assert(level >= 2, `prefix(), dotLast2Vbars but level=${OL(level)}`);
      return oneIndent.repeat(level - 2) + dotIndent + clearIndent;
    default:
      return oneIndent.repeat(level);
  }
};

// ---------------------------------------------------------------------------
export var addArrow = function(prefix) {
  var pos, result;
  pos = prefix.lastIndexOf(vbar);
  if (pos === -1) {
    result = prefix;
  } else {
    result = setCharsAt(prefix, pos, arrow);
  }
  return result;
};

// ---------------------------------------------------------------------------
export var removeLastVbar = function(prefix) {
  var pos, result;
  pos = prefix.lastIndexOf(vbar);
  if (pos === -1) {
    result = prefix;
  } else {
    result = setCharsAt(prefix, pos, ' ');
  }
  return result;
};
