// Generated by CoffeeScript 2.6.1
// arrow.coffee
export var vbar = '│'; // unicode 2502

export var hbar = '─'; // unicode 2500

export var corner = '└'; // unicode 2514

export var arrowhead = '>';

export var space = ' ';

export var oneIndent = vbar + space + space + space;

export var arrow = corner + hbar + arrowhead + space;

export var fourSpaces = space + space + space + space;

// ---------------------------------------------------------------------------
export var getPrefix = function(level, option = 'none') {
  var result;
  if (level === 0) {
    return '';
  }
  switch (option) {
    case 'withArrow':
      result = oneIndent.repeat(level - 1) + arrow;
      break;
    case 'returnVal':
      result = oneIndent.repeat(level - 1) + fourSpaces;
      break;
    case 'none':
      result = oneIndent.repeat(level);
      break;
    default:
      throw new Error(`getPrefix(): Bad option: '${option}'`);
  }
  if (result.length % 4 !== 0) {
    throw new Error(`getPrefix(): Bad prefix '${result}'`);
  }
  return result;
};
