// Generated by CoffeeScript 2.6.1
// browser_utils.coffee

// ---------------------------------------------------------------------------
//   beep - play a sound
export var beep = function(volume = 100, freq = 520, duration = 200) {
  var u, v;
  v = this.audio.createOscillator();
  u = this.audio.createGain();
  v.connect(u);
  v.frequency.value = freq;
  v.type = "square";
  u.connect(this.audio.destination);
  u.gain.value = volume * 0.01;
  v.start(this.audio.currentTime);
  v.stop(this.audio.currentTime + duration * 0.001);
};
