// Generated by CoffeeScript 2.5.1
  // env_lib.coffee
import {
  strict as assert
} from 'assert';

// --- Use by simply importing and using hEnv
//     This module does no loading - it merely holds hEnv
export var hEnvLib = {};

// --- None of these callbacks should replace variable hEnv
export var hEnvLibCallbacks = {
  getVar: function(name) {
    return hEnvLib[name];
  },
  setVar: function(name, value) {
    hEnvLib[name] = value;
  },
  clearVar: function(name) {
    delete hEnvLib[name];
  },
  clearAll: function() {
    var i, key, len, ref;
    ref = Object.keys(hEnv);
    for (i = 0, len = ref.length; i < len; i++) {
      key = ref[i];
      delete hEnvLib[name];
    }
  },
  names: function() {
    return Object.keys(hEnvLib);
  }
};
