// Generated by CoffeeScript 2.5.1
// log_utils.coffee
var logger, maxOneLine;

import {
  strict as assert
} from 'assert';

import yaml from 'js-yaml';

import {
  undef,
  isFunction,
  escapeStr,
  stringToArray
} from '@jdeighan/coffee-utils';

import {
  tabify
} from '@jdeighan/coffee-utils/indent';

import {
  debug
} from '@jdeighan/coffee-utils/debug';

logger = console.log; // for strings


// ---------------------------------------------------------------------------
// the default stringifier
export var tamlStringify = function(obj) {
  var str;
  str = yaml.dump(obj, {
    skipInvalid: true,
    indent: 1,
    sortKeys: false,
    lineWidth: -1
  });
  str = "---\n" + tabify(str);
  str = str.replace(/\t/g, '   '); // because fr***ing Windows Terminal
  // has no way of adjusting display
  // of TAB chars
  return str;
};

// ---------------------------------------------------------------------------
export var stringify = tamlStringify; // for non-strings


// ---------------------------------------------------------------------------
export var setLogger = function(func) {
  if (func != null) {
    assert(isFunction(func), "setLogger() not a function");
    logger = func;
  } else {
    logger = console.log;
  }
};

// ---------------------------------------------------------------------------
export var setStringifier = function(func) {
  if (func != null) {
    assert(isFunction(func), "setStringifier() not a function");
    stringify = func;
  } else {
    stringify = tamlStringify;
  }
};

// ---------------------------------------------------------------------------
export var currentLogger = function() {
  return logger;
};

// ---------------------------------------------------------------------------
export var currentStringifier = function() {
  return stringify;
};

// ---------------------------------------------------------------------------
maxOneLine = 32;

// ---------------------------------------------------------------------------
//   log - print to the console
export var log = function(...lArgs) {
  var esc, i, item, j, json, len, len1, line, nArgs, prefix, ref, ref1, str;
  // --- (str, item, prefix)
  console.log("enter log()");
  nArgs = lArgs.length;
  if (nArgs === 0) {
    return;
  }
  str = lArgs[0];
  if (nArgs >= 2) {
    item = lArgs[1];
  }
  if (nArgs >= 3) {
    prefix = lArgs[2];
  } else {
    prefix = '';
  }
  debug(`nArgs = ${nArgs}`);
  debug(`str = '${str}'`);
  debug("item", item);
  if (nArgs === 1) {
    logger(`${prefix}${str}`);
  } else if (item == null) {
    logger(`${prefix}${str} = undef`);
  } else if (isNumber(item)) {
    logger(`${prefix}${str} = ${item}`);
  } else if (isString(item)) {
    esc = escapeStr(item);
    if (esc.length <= maxOneLine) {
      logger(`${prefix}${str} = '${esc}'`);
    } else {
      logger(`${prefix}${str}:`);
      ref = stringToArray(item);
      for (i = 0, len = ref.length; i < len; i++) {
        line = ref[i];
        logger(`${prefix}   ${escapeStr(line)}`);
      }
    }
  } else {
    // --- It's some type of object
    json = JSON.stringify(item);
    if (json.length <= maxOneLine) {
      logger(`${prefix}${str} = ${json}`);
    } else {
      logger(`${prefix}${str}:`);
      ref1 = stringToArray(stringify(item));
      for (j = 0, len1 = ref1.length; j < len1; j++) {
        str = ref1[j];
        logger(`${prefix}   ${str}`);
      }
    }
  }
  debug("return from log()");
};

// ---------------------------------------------------------------------------
