// Generated by CoffeeScript 2.7.0
// placeholders.coffee
var hDefOptions;

import {
  assert,
  undef,
  defined,
  croak
} from '@jdeighan/coffee-utils';

hDefOptions = {
  pre: '__',
  post: '__'
};

// ---------------------------------------------------------------------------
export var phStr = function(name, hOptions = hDefOptions) {
  var post, pre;
  ({pre, post} = hOptions);
  return `${pre}${name}${post}`;
};

// ---------------------------------------------------------------------------
export var phReplace = function(str, hValues, hOptions = hDefOptions) {
  var post, pre;
  ({pre, post} = hOptions);
  return str.replace(RegExp(`${pre}([A-Za-z_][A-Za-z0-9_]*)${post}`, "g"), function(_, name) {
    return hValues[name];
  });
};
