// Generated by CoffeeScript 2.6.1
// private_env.coffee
import assert from 'assert';

import {
  log
} from '@jdeighan/coffee-utils/log';

// --- Use by simply importing and using hEnvLib
//     This module does no loading - it merely holds hEnvLib
export var hPrivEnv = {};

// --- None of these callbacks should replace variable hEnvLib
export var hPrivEnvCallbacks = {
  getVar: function(name) {
    return hPrivEnv[name];
  },
  setVar: function(name, value) {
    hPrivEnv[name] = value;
  },
  clearVar: function(name) {
    delete hPrivEnv[name];
  },
  clearAll: function() {
    var i, len, name, ref;
    ref = Object.keys(hPrivEnv);
    for (i = 0, len = ref.length; i < len; i++) {
      name = ref[i];
      delete hPrivEnv[name];
    }
  },
  names: function() {
    return Object.keys(hPrivEnv);
  }
};

// ---------------------------------------------------------------------------
export var setPrivEnvVar = function(name, value) {
  hPrivEnv[name] = value;
};

// ---------------------------------------------------------------------------
export var resetPrivEnv = function() {
  var i, len, name, ref;
  ref = Object.keys(hPrivEnv);
  for (i = 0, len = ref.length; i < len; i++) {
    name = ref[i];
    delete hPrivEnv[name];
  }
};

// ---------------------------------------------------------------------------
export var logPrivEnv = function() {
  var key, value;
  log("PRIVATE ENVIRONMENT:");
  for (key in hPrivEnv) {
    value = hPrivEnv[key];
    log(`   ${key} = '${value}'`);
  }
  log('-'.repeat(40));
};
