// Generated by CoffeeScript 2.5.1
  // private_env.coffee
import {
  strict as assert
} from 'assert';

// --- Use by simply importing and using hEnvLib
//     This module does no loading - it merely holds hEnvLib
export var hPrivEnv = {};

// --- None of these callbacks should replace variable hEnvLib
export var hPrivEnvCallbacks = {
  getVar: function(name) {
    return hPrivEnv[name];
  },
  setVar: function(name, value) {
    hPrivEnv[name] = value;
  },
  clearVar: function(name) {
    delete hPrivEnv[name];
  },
  clearAll: function() {
    var i, len, name, ref;
    ref = Object.keys(hPrivEnv);
    for (i = 0, len = ref.length; i < len; i++) {
      name = ref[i];
      delete hPrivEnv[name];
    }
  },
  names: function() {
    return Object.keys(hPrivEnv);
  }
};
