// Generated by CoffeeScript 2.7.0
  // svelte_utils.coffee
import {
  assert,
  isFunction
} from '@jdeighan/coffee-utils';

import {
  log
} from '@jdeighan/coffee-utils/log';

// ---------------------------------------------------------------------------
//   svelteSourceCodeEsc - to display source code for a *.starbucks page
export var svelteSourceCodeEsc = function(str) {
  return str.replace(/\</g, '&lt;').replace(/\>/g, '&gt;').replace(/\{/g, '&lbrace;').replace(/\}/g, '&rbrace;').replace(/\$/g, '&dollar;');
};

// ---------------------------------------------------------------------------
//   svelteHtmlEsc - after converting markdown
export var svelteHtmlEsc = function(str) {
  return str.replace(/\{/g, '&lbrace;').replace(/\}/g, '&rbrace;').replace(/\$/g, '&dollar;');
};

// ---------------------------------------------------------------------------
export var onInterval = function(func, secs, doLog = false) {
  var interval, ms;
  assert(isFunction(func), "onInterval(): 1st arg not a function");
  ms = Math.floor(1000 * secs);
  if (doLog) {
    log(`calling func every ${ms} ms.`);
  }
  interval = setInterval(func, ms);
  return function() {
    if (doLog) {
      log("destroying interval timer");
    }
    return clearInterval(interval);
  };
};
