// Generated by CoffeeScript 2.6.1
  // svelte_utils.coffee
import {
  onDestroy
} from 'svelte';

// ---------------------------------------------------------------------------
//   svelteSourceCodeEsc - to display source code for a *.starbucks page
export var svelteSourceCodeEsc = function(str) {
  return str.replace(/\</g, '&lt;').replace(/\>/g, '&gt;').replace(/\{/g, '&lbrace;').replace(/\}/g, '&rbrace;').replace(/\$/g, '&dollar;');
};

// ---------------------------------------------------------------------------
//   svelteHtmlEsc - after converting markdown
export var svelteHtmlEsc = function(str) {
  return str.replace(/\{/g, '&lbrace;').replace(/\}/g, '&rbrace;').replace(/\$/g, '&dollar;');
};

// ---------------------------------------------------------------------------
export var onInterval = function(func, secs) {
  var interval;
  interval = setInterval(func, Math.floor(1000 * secs));
  return onDestroy(function() {
    return clearInterval(interval);
  });
};
