// Generated by CoffeeScript 2.7.0
// taml.coffee
import yaml from 'js-yaml';

import {
  assert,
  croak,
  isTAML,
  fromTAML,
  toTAML
} from '@jdeighan/base-utils';

import {
  undef,
  defined,
  notdefined,
  OL,
  chomp,
  escapeStr,
  isString,
  isObject,
  isEmpty
} from '@jdeighan/coffee-utils';

import {
  splitLine
} from '@jdeighan/coffee-utils/indent';

import {
  firstLine,
  toArray,
  toBlock
} from '@jdeighan/coffee-utils/block';

import {
  slurpTAML
} from '@jdeighan/coffee-utils/fs';

export {
  isTAML,
  fromTAML,
  toTAML,
  slurpTAML
};
